<?php

namespace IAW\TorneoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FechaTorneoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FechaTorneoRepository extends EntityRepository
{
}
