<?php

namespace IAW\TorneoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TorneoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TorneoRepository extends EntityRepository
{
}
