iaw_torneo_homepage:
    path:     /helloworld
    defaults: { _controller: IAWTorneoBundle:Default:index }

iaw_torneo_index:
    path: /Fixture/index
    defaults: { _controller: IAWTorneoBundle:Torneo:index }

iaw_torneo_add:
    path: /Fixture/add
    defaults: { _controller: IAWTorneoBundle:Torneo:add }


iaw_torneo_create:
    path: /Fixture/create
    defaults: { _controller: IAWTorneoBundle:Torneo:create }
    methods: POST

iaw_partido_index:
    path: /editar/partidos/index
    defaults: { _controller: IAWTorneoBundle:Partido:index }

iaw_partido_edit:
    path: /editar/partidos/resultado/{id}
    defaults: { _controller: IAWTorneoBundle:Partido:edit }


iaw_partido_update:
    path: /update/partidos/resultado/{id}
    defaults: { _controller: IAWTorneoBundle:Partido:update }
    methods: [POST, PUT]
