iaw_torneo_homepage:
    path:     /helloworld
    defaults: { _controller: IAWTorneoBundle:Default:index }

iaw_torneo_index:
    path: admin/fixture/index
    defaults: { _controller: IAWTorneoBundle:Torneo:index }

iaw_torneo_add:
    path: admin/fixture/add
    defaults: { _controller: IAWTorneoBundle:Torneo:add }


iaw_torneo_create:
    path: admin/fixture/create
    defaults: { _controller: IAWTorneoBundle:Torneo:create }
    methods: POST

iaw_torneo_eliminar:
    path: admin/participante/eliminar/{id}
    defaults: { _controller: IAWTorneoBundle:Torneo:eliminar }

iaw_torneo_estadisticas:
    path: /estadisticas
    defaults: { _controller: IAWTorneoBundle:Torneo:estadisticas }

iaw_partido_index:
    path: /editor/partidos/index
    defaults: { _controller: IAWTorneoBundle:Partido:index }

iaw_partido_edit:
    path: /editor/partidos/resultado/{id}
    defaults: { _controller: IAWTorneoBundle:Partido:edit }


iaw_partido_update:
    path: /editor/partidos/resultado/update/{id}
    defaults: { _controller: IAWTorneoBundle:Partido:update }
    methods: [POST, PUT]

iaw_partido_view:
    path: /partido/view/{id}
    defaults: { _controller: IAWTorneoBundle:Partido:view }

iaw_partido_verPartidos:
    path: /partidos/
    defaults: { _controller: IAWTorneoBundle:Partido:verPartidos }

iaw_partido_resultadosPartidos:
  path: /partidos/resultados
  defaults: { _controller: IAWTorneoBundle:Partido:resultadosPartidos }
