iaw_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: IAWUserBundle:Default:index }

iaw_user_index:
    path: /admin/index
    defaults: { _controller: IAWUserBundle:User:index }

iaw_user_add:
    path: /admin/add
    defaults: { _controller: IAWUserBundle:User:add }

iaw_user_create:
    path: /admin/create
    defaults: { _controller: IAWUserBundle:User:create }
    methods:  POST

iaw_user_edit:
    path: /admin/edit/{id}
    defaults: { _controller: IAWUserBundle:User:edit }

iaw_user_update:
    path: /admin/update/{id}
    defaults: { _controller: IAWUserBundle:User:update }
    methods: [POST, PUT]

iaw_user_view:
    path: /admin/view/{id}
    defaults: { _controller: IAWUserBundle:User:view }

iaw_user_delete:
    path: /admin/delete/{id}
    defaults: { _controller: IAWUserBundle:User:delete }
    methods: [POST, DELETE]


# Si se trata ingresar por url directo a /user/create,
# luego se redirecciona a /user/add.
iaw_user_redirect_add:
    path: /user/create
    defaults:
        _controller: IAWUserBundle:User:add
        path: /user/add
        permanent: true

# Si se trata ingresar por url directo a /user/update,
# luego se redirecciona a /user/edit.
iaw_user_redirect_edit:
    path: /user/update/{id}
    defaults:
        _controller: IAWUserBundle:User:edit
        path: /user/editar/{id}
        permanent: true


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_passwords:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
