<?php

namespace IAW\ParticipanteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PuntajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PuntajeRepository extends EntityRepository
{
}
