iaw_participante_homepage:
    path:     /pa
    defaults: { _controller: IAWParticipanteBundle:Default:index }

iaw_participante_index:
    path: /participante/index
    defaults: { _controller: IAWParticipanteBundle:Participante:index }

iaw_participante_add:
    path: admin/participante/add
    defaults: { _controller: IAWParticipanteBundle:Participante:add }

iaw_participante_create:
    path: admin/participante/create
    defaults: { _controller: IAWParticipanteBundle:Participante:create }
    methods:  POST

iaw_participante_edit:
    path: admin/participante/edit/{id}
    defaults: { _controller: IAWParticipanteBundle:Participante:edit }

iaw_participante_update:
    path: admin/participante/update/{id}
    defaults: { _controller: IAWParticipanteBundle:Participante:update }
    methods: [POST, PUT]

iaw_participante_view:
    path: /participante/view/{id}
    defaults: { _controller: IAWParticipanteBundle:Participante:view }

iaw_participante_delete:
    path: admin/participante/delete/{id}
    defaults: { _controller: IAWParticipanteBundle:Participante:delete }


iaw_jugador_add:
    path: admin/jugador/add/{participanteID}
    defaults: { _controller: IAWParticipanteBundle:Jugador:add }

iaw_jugador_create:
    path: admin/jugador/create/{participanteID}
    defaults: { _controller: IAWParticipanteBundle:Jugador:create }
    methods:  POST


# Si se trata ingresar por url directo a /participante/create,
# luego se redirecciona a /participante/add.
iaw_participante_redirect_add:
    path: admin/participante/create
    defaults:
        _controller: IAWParticipanteBundle:Participante:add
        path: admin/participante/add
        permanent: true

# Si se trata ingresar por url directo a /participante/update,
# luego se redirecciona a /participante/edit.
iaw_participante_redirect_edit:
    path: admin/participante/update/{id}
    defaults:
        _controller: IAWParticipanteBundle:Participante:edit
        path: admin/participante/editar/{id}
        permanent: true
